//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestersDictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        public int Id { get; set; }
        public string Понятие { get; set; }
        public string Определение { get; set; }
        public string Источники { get; set; }
    }
}
